services:
  # backend:
  #   image:
  #   container_name: genca_backend
  #   restart: always
  #   env_file:
  #     - ./src/.env
  db:
    image: postgres
    container_name: storedb
    restart: always
    env_file:
      - ./src/.env
    ports:
      - "5432:5432"
    volumes:
      - vol_postgres:/var/lib/postgresql/data
    networks:
      - genca_network

networks:
  genca_network:
volumes:
  vol_postgres:
